import type React from "react";
import { Teachers } from "next/font/google";
import { Metadata } from "next";
import AppWalletProvider from "./providers/AppWalletProvider";
import "./globals.css";
import QueryProvider from "./providers/query";

const teacher = Teachers({
  subsets: ["latin"],
  variable: "--font-teacher",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${teacher.variable} font-sans`}>
        <QueryProvider>
          <AppWalletProvider>{children}</AppWalletProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
