import type React from "react";
import { Teachers } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { Metadata } from "next";
import AppWalletProvider from "./components/AppWalletProvider";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";

const teacher = Teachers({
  subsets: ["latin"],
  variable: "--font-teacher",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${teacher.variable} font-sans`}>
        <AppWalletProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <SidebarProvider defaultOpen={false} className="justify-center">
              {children}
            </SidebarProvider>
          </ThemeProvider>
        </AppWalletProvider>
      </body>
    </html>
  );
}
